# Generated by Django 5.2.4 on 2025-07-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_offer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="code",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="offer",
            name="description",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.ImageField(upload_to="products/"),
        ),
    ]
